// Seperate CallerID generation/request 
// client side application 
// input to the API
var input = {"CallerID": 9083457983045, 	// generated by client app, unique value, can be used to track caller refreshing their location
             "BTs": [{"Major": 101, "Minor": 156, "RSSI": -70}, {"Major": 101, "Minor": 191, "RSSI": -81}]} // requires at least 4 for trilateration

// deviation will be dependent on an equation - radius in which user could be in from trilateration algorithm
// avg rssi is the average if multiple of the same BT device is inputed
// Output to the Operator from the phone
var output = {"CallerID": "-KwO0rG2BjlR3A7TaAs8", "err_x": 0.249189723, "err_y": 0.43552345, "est_x": 7.8856462767156135, "est_y": 20.129574628039563, "est_floor": 2, "est_room": 229
//              "BTs": [{"Major": 101, "Minor": 156, "avg_rssi": -43.11324, "floor": 2, "real_x": -53.234123, "real_y": 10.3423412},
//                     ...,
//                     {"Major": 101, "Minor": 156, "avg_rssi": -43.11324, "floor": 2, "real_x": -53.234123, "real_y": 10.3423412}]
             }

// Algorithmn side, -> not sure

var json = {"deviation": 6.90362902791986, "y0": 14.143063062636797, "x0": 14.637740274126605,
            "BTs": [{"min": 147, "proximity": 2, "floor": 2, "avg_rssi": -53.892276795284445, "y": 12.526937613537996, "x": 11.15477383840724, "maj": 101}, {"min": 138, "proximity": 2, "floor": 2, "avg_rssi": -59.450359729600315, "y": 15.484317613781835, "x": 18.575287609270795, "maj": 101}, {"min": 140, "proximity": 5, "floor": 2, "avg_rssi": -65.71391254656905, "y": 15.634693066409822, "x": 7.394378665219882, "maj": 101}], 
            "real_y": 14.196893569939407, "real_x": 7.7343211189817245, "real_floor": 2, "est_floor": 2}

// testing code
var config = {
	apiKey: "AIzaSyCCpIjWcPGeqdmnk6CcDABpyly7BrQZNhg",
	authDomain: "maptechnology-1506012449347.firebaseapp.com",
	databaseURL: "https://maptechnology-1506012449347.firebaseio.com",
	projectId: "maptechnology-1506012449347",
	storageBucket: "maptechnology-1506012449347.appspot.com",
	messagingSenderId: "365861832460"
};
firebase.initializeApp(config);
var data = {}
var userid = firebase.database().ref('test').push().key;
data[userid] = {cx: 0, cy: 0, rx: 5, ry: 5, floor: 2, room: 229};
firebase.database().ref('test').update(data);
firebase.database().ref('test/'+userid).onDisconnect().remove();

function unconvert(x) {
	x = x * 1/72;
	x = x * 25;
	x = x * 1/3.28084;
	return x;
}

var t = Snap(850, 1100);
var c = t.circle(162, 721, 10);

var move = function(dx,dy) {
	// console.log(this.transform().local);
	// console.log(unconvert(dx));
	if (this.transform().local) {
		var list = this.transform().local.slice(1).split(',');
		// console.log(list);
		data[userid]["cx"] = 162 + parseFloat(list[0]);
		data[userid]["cy"] = 721 + parseFloat(list[1]);
	}
	// data[userid]["cx"] = data[userid]["cx"] + unconvert(dx);
	// data[userid]["cy"] = data[userid]["cy"] + unconvert(dy);
	firebase.database().ref('test/'+userid).update(data[userid]);
	this.attr({
		transform: this.data('origTransform') + (this.data('origTransform') ? "T" : "t") + [dx, dy]
	});
}
var start = function() {
	this.data('origTransform', this.transform().local );
}
var stop = function() {
	console.log('finished dragging');
}

var sliderX = document.getElementById('locationX');
var sliderY = document.getElementById('locationY');
sliderX.oninput = function() {
	data[userid]["rx"] = this.value;
	firebase.database().ref('test/'+userid).update(data[userid]);
}
sliderY.oninput = function() {
	data[userid]["ry"] = this.value;
	firebase.database().ref('test/'+userid).update(data[userid]);
}

c.drag(move, start, stop);